### PR TITLE
Proposed approach for bundling data and creating executable scripts

### PR DESCRIPTION
**Pull request by ajkessel**
Suggest using pyproject.toml rather than old-style setup.py; package data files and provide access to same via importlib; make CLIs executable in venv.

### CODE REVIEW

**Comment by rsxdalv** [comment]
What about the scripts accessing `./data`, for example:

eval_infer_batch.py has such code:
```python
if testset == "ls_pc_test_clean":
    metalst = "data/librispeech_pc_test_clean_cross_sentence.lst"
    librispeech_test_clean_path = "<SOME_PATH>/LibriSpeech/test-clean"  # test-clean path
    metainfo = get_librispeech_test_clean_metainfo(metalst, librispeech_test_clean_path)
```

And as for the execution, do you reckon that this is only accessible via `git clone` `pip install -r requirements` `cd src/f5_tts` route?

Currently the scripts are broken unless using `python -m` because they use global imports.

**Comment by ajkessel** [comment]
In my view, all of the user-executable scripts should be added to `[project.scripts]` in `pyproject.toml`. The scripts might need tweaking along the lines of what I did to `inference-cli.py`.

I just updated the PR to show what I would do with eval_infer_batch, although some of those data files (e.g. `meta.lst`) aren't currently in the repo.

**Comment by rsxdalv** [comment]
Alright, I tested this for inference and it's all good, so I will merge it in and continue work from there.

**Comment by rsxdalv** [comment]
Thank you for your improvements and suggestions.

**Comment by ajkessel** [comment]
Thanks for accepting! Happy to continue to help. Are you interested in pushing to pypi if upstream doesn't want to do that?

**Comment by rsxdalv** [comment]
I'll make a github workflow for pushing to pypi, and even if we have to
wait I'd rather consolidate on the main project. If you are familiar with
RVC it suffers from huge fragmentation that I'd like to avoid.

**Comment by ajkessel** [comment]
Do you understand what's going on with `seedtts_testset`? It doesn't seems to be something that is in the repo--is it something the script itself downloads in response to a command? If so, we probably want to put it somewhere else, not in the package data folder as I did with my patch. 

More generally, we can probably provide a useful service by looking at every hardcoded path and figuring out what the more portable/standard way to do it would be.

**Comment by rsxdalv** [comment]
I have a bigger issue for now, when using within my app gradio breaks down.

**Comment by rsxdalv** [comment]
> I have a bigger issue for now, when using within my app gradio breaks down.

Ok, turns out it's because of this code:
```python
    max_speech_types = 100
    speech_type_names = []
    speech_type_audios = []
    speech_type_ref_texts = []
    speech_type_delete_btns = []

    for i in range(max_speech_types - 1):
        with gr.Row():
```

As for the `seedtts_testset` I think once again that the package has 2 distinct use cases, and this is the `git clone...` style.
Once I have the time, I will look at how older repos do it, like Audiocraft or Parler TTS, which also provide fine tuning capabilities.

**Comment by ajkessel** [comment]
> Ok, turns out it's because of this code:

Is this related to my proposed packaging/refactoring, or an unrelated issue? I don't think I modified that code other than to put everything in the cli's under a `main()` function.

**Comment by rsxdalv** [comment]
No, it just coincided. I am not even sure why it was able to run before,
rather than fail from the start.

**Comment by SWivid** [comment]
@rsxdalv @ajkessel Hi there~ Would it sound good like:

- pip package for inference-only usage
- local editable for extra training/finetuning/evaluation

A basic structure (dependencies not solved yet, will start tomorrow when I wake up):
https://github.com/SWivid/F5-TTS/tree/dev

README.md will split to each part.
Inference will use the vocab.txt file `src/f5_tts/infer/examples/vocab.txt`
Training/finetuning/evaluation just go for `/data` outside

**Comment by ajkessel** [comment]
Thanks @SWivid . That looks right to me. From my perspective, it makes sense to have a developer's use-case (training/finetuning/eval) and an end-user's use-case (TTS invoked from some other python script, internals are invisible).

**Comment by rsxdalv** [comment]
That looks great!
Inference should be 90% of the external use cases, and anyone looking to do
training could still install manually.

**Pull request merged**
